# Generated by Django 5.1.6 on 2025-02-08 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_subcategory', to='products.subcategory', verbose_name='Подкатегория'),
        ),
    ]
